language: python
sudo: required

python:
  - 2.7

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libudev-dev libusb-1.0.0-dev

install:
  - pip install -r dev-requirements.txt
  - pip install -e .

script:
  - coverage run setup.py test

after_success:
  - coveralls
